name: test

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - uses: dschep/install-pipenv-action@v1
    
    - name: Cache Python dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }} 
      
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true' 
      run: pipenv install -d
    
    - name: Run test
      run: |
        pipenv run coverage run --source mooncell_text -m unittest discover -s tests
        pipenv run coverage xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        
